name: flutter_application_1
description: "Flutter project with clean archicture and clean UI design."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  delightful_toast: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.14
  freezed_annotation: ^2.4.4
  go_router: ^14.6.0
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter_gen:
  output: lib/src/core/utils/gen/
  line_length: 80
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/json/

  fonts:
    - family: RocaTwoLight
      fonts:
        - asset: assets/fonts/roca_two_light/roca-two-light.ttf
